version: "3"

services:
  php:
    build: ./.docker/php
    volumes:
      - .:/app
    working_dir: /app

  queue:
    build: ./.docker/php
    volumes:
      - .:/app
    working_dir: /app

  nginx:
    image: nginx:alpine
    volumes:
      - .:/app:ro
    working_dir: /app
    depends_on:
      - php

  nodejs:
    image: node:lts-alpine3.17
    volumes:
      - .:/app
    working_dir: /app

  redis:
    image: redis:7.0.9-alpine3.17
    volumes:
      - ./.docker/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
